services:
  - type: web
    name: goldenberry-ticket-bot
    plan: free
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: TOKEN
        sync: false # You will need to set this manually in Render dashboard
      - key: CLIENT_ID
        value: 1496869352115404820
      - key: GUILD_ID
        value: 1496756076370985010
      - key: EXCHANGER_ROLE_ID
        value: 1496874165440090202
      - key: TICKET_CATEGORY_ID
        value: 1496870335998333058
      - key: LOG_CHANNEL_ID
        value: 1496874669498830958
